### ISSUE TITLE
Menu display needs spacing

### ISSUE THREAD

**Issue by darrenmckenna** [mkdo/nhs-theme#12]
The menu items run into each other without any spacing when displayed horizontally.

**Comment by nervewax** [comment]
@darrenmckenna thanks for taking interest and flagging this up, we're actually having a meeting with the folks at nhs.uk this Friday (26th), and following that, rebuilding this theme from the ground up using the new official [NHS frontend framework](https://nhsuk.github.io/nhsuk-frontend/)

Apologies if you've started using this recently, we should have something much better up here soon.
